#############################################
#        WARNING! FOR EXPERTS ONLY!         #
#  This is personalDNSfilter configuration! #
# Only edit this file if you are an expert! #
#############################################

detectDNS = true

fallbackDNS = \
    1.1.1.2::853::DoT::security.cloudflare-dns.com; \
    1.0.0.2::853::DoT::security.cloudflare-dns.com; \
    9.9.9.9::853::DoT::dns.quad9.net

passcode = 

ipVersionSupport = 46

ipV4BlockedHost = 0.0.0.0
ipV6BlockedHost = ::

maxResolverCount = 6

enableLocalResolver = true

localResolverTTL = 600

resolveOverHttpProxy = false
httpProxyHost = my.proxy
httpProxyIP = 10.0.2.2
httpProxyPort = 8080
httpProxyBasicAuthStr = 

routeUnderlyingDNS = true

routeIPs = 8.8.8.8; 8.8.4.4; 1.1.1.1; 1.0.0.1

AUTOSTART = true

androidAppWhiteList = <none>

dnsProxyOnAndroid = false

dnsProxyPortAndroid = 5300

dnsProxyPortNonAndroid = 53

dnsProxyOnlyLocalRequests = true

rootModeOnAndroid = false

vpnInAdditionToProxyMode = false

androidKeepAwake = true

manageDNSCryptProxy = false

dnsCryptProxyStartOptions = -config /system/etc/dnscrypt-proxy/dnscrypt-proxy.toml

enableTrafficLog = false
trafficLogName = trafficlog
trafficLogSize = 1048576
trafficLogSlotCount = 2

client_remote_ctrl_host = 0.0.0.0
client_remote_ctrl_keyphrase = Change This Default Keyphrase!
client_remote_ctrl_port = 3333

server_remote_ctrl_keyphrase = Change This Default Keyphrase!
server_remote_ctrl_port = -1

debug = false

dnsRequestTimeout = 5000

filterHostsCacheSize = 20000

allowedHostsCacheSize = 20000

checkResolvedIP = false

checkCNAME = true

filterHostsFile = FILTERHOSTS.TXT

filterActive = true

filterAutoUpdateURL = \
    https://raw.githubusercontent.com/somafix/dns-blocklist/main/dynamic-blocklist.txt; \
    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts; \
    https://adaway.org/hosts.txt; \
    https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/ultimate.txt

filterAutoUpdateURL_IDs = \
    dynamic-live; \
    stevenblack; \
    adaway; \
    hagezi-ultimate

filterAutoUpdateURL_categories = \
    dynamic; \
    ads; \
    ads; \
    ultimate

filterAutoUpdateURL_switchs = \
    true; true; true; true

previousAutoUpdateURL = 

reloadIntervalDays = 1

filterLogFormat = <font color='#E53935'>($CONTENT)</font>
acceptLogFormat = <font color='#43A047'>($CONTENT)</font>
fwdLogFormat = <font color='#FFB300'>($CONTENT)</font>
normalLogFormat = ($CONTENT)
logTextSize = 14

repeatingLogSuppressTime = 2000

addLiveLogTimestamp = true
liveLogTimeStampFormat = '<font color=''#8c8c8c''><strong>'HH:mm:ss'</strong></font>'

footerLink = <font color='#ffffff'><strong><a href='https://www.zenz-solutions.de/personaldnsfilter-wp/'>WEBSITE</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='https://www.zenz-solutions.de/donations'>DONATE</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='https://www.zenz-solutions.de/personaldnsfilter-privacy/'>PRIVACY</a></strong></font>

showInitialInfoPopUp = true
initialInfoPopUpTitle = Consider your rating!
initialInfoPopUpText = Thanks for using our free app personalDNSfilter!<br><br>Please ensure <strong>private DNS is disabled</strong> in Android network settings. When enabled, personalDNSfilter might be bypassed!<br><br>In addition allow personalDNSfilter to <strong>run unrestricted in background without battery optimization</strong> as otherwise Android might kill the service!<br><br>Sometimes we get bad ratings due to misunderstanding. Therefore, before rating, please check our <a href='https://www.zenz-home.com/personaldnsfilter/help/faq.php'>FAQ</a></strong>, or ask our <a href='https://telegram.me/pdnsf'>Telegram group</a></strong>.

dumpDNSPerfInfo = false

useActionMenuFallback = false

forceAndroidDisplayMode = none
