name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false  # ОТКЛЮЧАЕМ КЭШ НАХУЙ
      
      - name: Clean cache
        run: |
          go clean -cache -modcache
          rm -rf ~/.cache/go-build
      
      - name: Run
        run: go run main.go
