name: Update HaGeZi Blocklist

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run update script
        run: python update.py

      - name: Push back to repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add hosts.txt
          git commit -m "Обновление HaGeZi PRO++ от $(date +'%Y-%m-%d')" || echo "Нет изменений"
          git push origin main --force
          exit 0
